akiko:
  port: 7_000
  exec_env: "Development"
  engines:
    # put all ur engines here starting with the name, the name of their binary
    # and its token.
    stockfish:
      name: "Stockfish" # make sure that this is the folder where your engine is
      exec: "./engines/Stockfish/src/stockfish" # The command to run your bot.
      token: "lip_xxxxXXXXxxxx" # and ofc put your token here

    # and just keep going like this
    engine_two:
      name: "mysecondengine"
      exec: "java -jar -Xmx4096 -Xms1024 ./engines/myengine/release/engine.jar"
      token: "lip_xxxxXXXXxxxx"
